// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Author struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Books     []*Book   `json:"books"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Book struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Author    *Author   `json:"author"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CreateAuthorInput struct {
	Name string `json:"name"`
}

type CreateBookInput struct {
	Title    string `json:"title"`
	AuthorID string `json:"authorId"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBookInput struct {
	Title    string `json:"title"`
	AuthorID string `json:"authorId"`
}
